---
- name: Playlist to create user and give the password from secret files
  hosts: dev, test
  vars_files:
    - user_list.yml
    - locker_now.yml  
  tasks:
    - name: Create a supplementary group
      ansible.builtin.group:
        name: devops
        state: present
      
    - name: Create the users and groups
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: devops
        password: "{{ PW_developer | password_hash('sha512') }}"
      loop: "{{ myusers }}"
      when: item.job == 'developer'    

- name: Playlist to create user and give the password from secret files
  hosts: prod
  vars_files:
    - user_list.yml
    - locker_now.yml
  tasks:
    - name: Create a supplementary group
      ansible.builtin.group:
        name: opsmgr
        state: present

    - name: Create the users and groups
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: opsmgr
        password: "{{ PW_manager | password_hash('sha512') }}"
      loop: "{{ myusers }}"
      when: item.job == 'manager'           
